import train from '@/presentation/views/Home/components/Guides/utils/assets/train.png';

export const guidesItems = [
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 70.91,
    score: 5,
    profileUrl: 'https://example.com/nature/6130',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 70.45,
    score: 5,
    profileUrl: 'https://example.com/nature/1167',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 52.99,
    score: 5,
    profileUrl: 'https://example.com/nature/8357',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 60.08,
    score: 5,
    profileUrl: 'https://example.com/nature/5080',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 56.69,
    score: 5,
    profileUrl: 'https://example.com/nature/9829',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 72.04,
    score: 5,
    profileUrl: 'https://example.com/nature/3600',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 72.98,
    score: 5,
    profileUrl: 'https://example.com/nature/2648',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 66.97,
    score: 5,
    profileUrl: 'https://example.com/nature/4976',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 64.15,
    score: 5,
    profileUrl: 'https://example.com/nature/8712',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 64.94,
    score: 5,
    profileUrl: 'https://example.com/nature/2922',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 54.01,
    score: 5,
    profileUrl: 'https://example.com/nature/9778',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 74.23,
    score: 5,
    profileUrl: 'https://example.com/nature/8319',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 74.62,
    score: 5,
    profileUrl: 'https://example.com/nature/3770',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 62.67,
    score: 5,
    profileUrl: 'https://example.com/nature/8594',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 57.99,
    score: 5,
    profileUrl: 'https://example.com/nature/8244',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 60.41,
    score: 5,
    profileUrl: 'https://example.com/nature/3831',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 58.3,
    score: 5,
    profileUrl: 'https://example.com/nature/8079',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 57.98,
    score: 5,
    profileUrl: 'https://example.com/nature/1413',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 79.06,
    score: 5,
    profileUrl: 'https://example.com/nature/7227',
  },
  {
    image: train,
    location: 'curitiba',
    title: 'Nature Tour',
    lowestTourPrice: 61.73,
    score: 5,
    profileUrl: 'https://example.com/nature/2896',
  },
];
